language: minimal

services:
  - docker

before_install:
  # Install AWS CLI
  - sudo apt-get install awscli
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set region $AWS_REGION

script:
  # Build the Docker image
  - docker build -t workouts-frontend:latest -f Dockerfile .

  # Create the ECR repo
  - aws ecr create-repository --repository-name workouts-frontend --region $AWS_REGION

  # Tag the Docker image with the ECR repository URL
  - docker tag workouts-frontend:latest 549538177002.dkr.ecr.$AWS_REGION.amazonaws.com/workouts-frontend:latest

  # Log in to ECR
  - eval $(aws ecr get-login --no-include-email --region $AWS_REGION)

  # Push the Docker image to ECR
  - docker push 549538177002.dkr.ecr.$AWS_REGION.amazonaws.com/workouts-frontend:latest
# deploy:
#   provider: script
#   script:
#     # Pull the image from ECR
#     # - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin <your-ecr-repository-url>

#     # # Log in to ECR
#     # - eval $(aws ecr get-login --no-include-email --region $AWS_REGION)

#     # Pull the Docker image from ECR
#     - docker pull 549538177002.dkr.ecr.$AWS_REGION.amazonaws.com/workouts-frontend:latest

#     # Deploy the image to ECS
#     - aws ecs update-service --cluster <your-ecs-cluster> --service <your-ecs-service> --force-new-deployment
